version: '3'
services:
  mainapp:
    build: .
    ports:
    - "80:80"
    volumes:
    - /Users/dierick/F5 Networks/GitHub/arcadia-finance/MainApp/:/var/www/html/
    image: arcadia_mainapp
  backend:
    build: .
    ports:
    - "8080:80"
    volumes:
    - /Users/dierick/F5 Networks/GitHub/arcadia-finance/files/:/var/www/html/files/
    image: arcadia_backend
